cart/urls.py
# cart/urls.py

from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import AddToCartView, ViewCartView, RemoveFromCartView, UpdateCartView, cart_view, CheckoutView, checkout, order_confirmation

from .views import APIRootView




# Router configuration
router = DefaultRouter()
router.register(r'cart', ViewCartView, basename='view_cart')

urlpatterns = [
    path('', APIRootView.as_view(), name='api_root'),  # API root endpoint
    path('cart/add/<int:product_id>/', AddToCartView.as_view({'post': 'add'}), name='add_to_cart'),
    path('cart/remove/', RemoveFromCartView.as_view({'post': 'remove'}), name='remove_from_cart'),
    path('cart/update/<int:product_id>/', UpdateCartView.as_view({'post': 'update'}), name='update_cart'),
    path('cart/view/', cart_view, name="cart_view"),
    path('checkout/', checkout, name='checkout'),
    path('order/confirmation/<int:order_id>/', order_confirmation, name='order_confirmation'),
]

urlpatterns += [
    path('cart/', ViewCartView.as_view(), name='view-cart'),
    path('checkoutapi/', CheckoutView.as_view(), name='checkoutapi'),
]

store_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('vendors/', include('vendors.urls')),
    path('customers/', include('customers.urls')),
    path('', include('main.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendors/urls.py
from django.urls import path
from .views import AddProductView, product_list, ProductUpdateView, seller_dashboard, manage_sellers, manage_products, reports, category_list, category_create, category_update, category_delete, delete_product, discount_list, discount_create, discount_update, discount_delete
from .views import order_list, vendor_products_with_reviews

urlpatterns = [
    path('manage_sellers/', manage_sellers, name='manage_sellers'),
    path('manage_products/', manage_products, name='manage_products'),
    path('reports/', reports, name='reports'),
    path('products/', product_list, name='product_list'),
    path('product/edit/<int:pk>/', ProductUpdateView.as_view(), name='edit_product'),
    path('delete-product/<int:product_id>/', delete_product, name='delete_product'),
    path('dashboard/', seller_dashboard, name='seller_dashboard'),
    path('add_product/', AddProductView.as_view(), name='add_product'),
    path('category/', category_list, name='category_list'),
    path('category/new/', category_create, name='category_create'),
    path('category/<int:pk>/edit/', category_update, name='category_update'),
    path('category/<int:pk>/delete/', category_delete, name='category_delete'),

    path('discount/', discount_list, name='discount_list'),
    path('discount/new/', discount_create, name='discount_create'),
    path('discount/<int:pk>/edit/', discount_update, name='discount_update'),
    path('discount/<int:pk>/delete/', discount_delete, name='discount_delete'),
    path('orders/', order_list, name='vendor_orders'),
    path('vendor-reviewes', vendor_products_with_reviews, name='vendor_products_with_reviews'),

]

vendors/models.py
from django.db import models
from django_jalali.db import models as jmodels


class Category(models.Model):
    name = models.CharField(max_length=100)
    seller = models.ForeignKey('accounts.SellerProfile', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=0)
    sales_count = models.PositiveIntegerField(default=0)
    discount = models.DecimalField(max_digits=10, default=0, decimal_places=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    seller = models.ForeignKey('accounts.SellerProfile', on_delete=models.CASCADE)
    created_at = jmodels.jDateTimeField(auto_now_add=True)  # datetime in jalali #datetime
    updated_at = jmodels.jDateTimeField(auto_now_add=True)  # datetime in jalali
    image = models.ImageField(upload_to='product_images/', null=True, blank=True)  # فیلد جدید برای تصویر

    def get_final_price(self):
        discount = Discount.objects.filter(product=self).first()
        if discount:
            if discount.discount_type == 'percentage':
                return self.price * (1 - (discount.value / 100))
            elif discount.discount_type == 'fixed':
                return self.price - discount.value
        return self.price

    def __str__(self):
        return self.name


class Discount(models.Model):
    DISCOUNT_TYPES = [
        ('fixed', 'ثابت'),
        ('percentage', 'درصدی'),
    ]

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='discounts')
    seller = models.ForeignKey('accounts.SellerProfile', on_delete=models.CASCADE)
    discount_type = models.CharField(max_length=50, choices=DISCOUNT_TYPES)  # نوع تخفیف
    value = models.DecimalField(max_digits=10, decimal_places=0)  # مقدار تخفیف

vendors/forms.py
from django import forms
from .models import Category, Discount, Product


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
            'name': 'نام دسته‌بندی',
        }


class DiscountForm(forms.ModelForm):
    class Meta:
        model = Discount
        fields = ['product', 'discount_type', 'value']
        labels = {
            'product': 'محصول',
            'discount_type': 'نوع تخفیف',
            'value': 'مقدار تخفیف',
        }

    discount_type = forms.ChoiceField(choices=Discount.DISCOUNT_TYPES, label='نوع تخفیف')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category', 'image']
        labels = {
            'name': 'نام محصول',
            'description': 'توضیحات محصول',
            'price': 'قیمت',
            'category': 'دسته‌بندی',
            'image': 'تصویر محصول',
        }











    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="انتخاب دسته‌بندی", label=' دسته‌بندی')

    def save(self, commit=True):
        product = super().save(commit)
        
        if commit:
            product.save()  
        return product

vendors/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Category, Discount
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CategoryForm, DiscountForm, ProductForm
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import UpdateView
from django.urls import reverse_lazy
from accounts.models import SellerProfile
from django.views.generic import ListView
from cart.models import Order


def category_list(request):
    categories = Category.objects.filter(seller=request.user.sellerprofile)
    return render(request, 'vendors/category_list.html', {'categories': categories})


def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.seller = request.user.sellerprofile  # هر دسته‌بندی برای فروشنده مشخصی باشد
            category.save()
            return redirect('category_list')
    else:
        form = CategoryForm()
    return render(request, 'vendors/category_form.html', {'form': form})


def category_update(request, pk):
    category = get_object_or_404(Category, pk=pk,
                                 seller=request.user.sellerprofile)  # استعلام دسته‌بندی مربوط به فروشنده
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('category_list')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'vendors/category_form.html', {'form': form})


def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk,
                                 seller=request.user.sellerprofile)  # استعلام دسته‌بندی مربوط به فروشنده
    if request.method == 'POST':
        category.delete()
        return redirect('category_list')
    return render(request, 'vendors/category_confirm_delete.html', {'category': category})


# CRUD for discount


def discount_list(request):
    discounts = Discount.objects.filter(seller=request.user.sellerprofile)
    return render(request, 'vendors/discount_list.html', {'discounts': discounts})


def discount_create(request):
    if request.method == 'POST':
        form = DiscountForm(request.POST)
        if form.is_valid():
            discount = form.save(commit=False)
            discount.seller = request.user.sellerprofile  # تخصیص به فروشنده
            discount.save()
            messages.success(request, 'تخفیف با موفقیت ایجاد شد.')
            return redirect('discount_list')
    else:
        form = DiscountForm()
    return render(request, 'vendors/discount_form.html', {'form': form})


def discount_update(request, pk):
    discount = get_object_or_404(Discount, pk=pk, seller=request.user.sellerprofile)
    if request.method == 'POST':
        form = DiscountForm(request.POST, instance=discount)
        if form.is_valid():
            form.save()
            messages.success(request, 'تخفیف با موفقیت ویرایش شد.')
            return redirect('discount_list')
    else:
        form = DiscountForm(instance=discount)
    return render(request, 'vendors/discount_form.html', {'form': form})


def discount_delete(request, pk):
    discount = get_object_or_404(Discount, pk=pk, seller=request.user.sellerprofile)
    if request.method == 'POST':
        discount.delete()
        messages.success(request, 'تخفیف با موفقیت حذف شد.')
        return redirect('discount_list')  # تغییر به لیست تخفیف‌ها
    return render(request, 'vendors/discount_confirm_delete.html', {'discount': discount})


@login_required
def seller_dashboard(request):
    try:
        seller_profile = request.user.sellerprofile
    except SellerProfile.DoesNotExist:
        seller_profile = None  #می توانید ایجاد نمایه جدید یا تغییر مسیر را تنظیم کنید

    context = {
        'seller_profile': seller_profile,
    }
    return render(request, 'vendors/dashboard.html', context)


class AddProductView(FormView):
    template_name = 'vendors/add_product.html'
    form_class = ProductForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        product = form.save(commit=False)
        product.seller = self.request.user.sellerprofile  # Seller را تنظیم کن
        product.save()  # ذخیره محصول

        messages.success(self.request, 'محصول با موفقیت اضافه شد')
        return redirect('product_list')

    def form_invalid(self, form):
        messages.error(self.request, 'مشکلی در ارسال اطلاعات وجود دارد.')
        return self.render_to_response(self.get_context_data(form=form))


class ProductUpdateView(SuccessMessageMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'vendors/edit_product.html'
    success_message = "محصول با موفقیت ویرایش شد"
    success_url = reverse_lazy('product_list')

    def form_valid(self, form):
        # در صورتی که نیاز به انجام کاری خاص بعد از اعتبارسنجی فرم دارید اینجا اضافه کنید
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = self.object  # به محصول جاری دسترسی پیدا کنید
        return context


@login_required
def product_list(request):
    products = Product.objects.filter(seller=request.user.sellerprofile)
    return render(request, 'vendors/product_list.html', {'products': products})


@login_required
def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        product.delete()
        messages.success(request, 'محصول با موفقیت حذف شد.')
        return redirect('product_list')  # فرض می‌کنیم که نام آدرس مربوط به لیست محصولات 'product_list' است.

    return render(request, 'vendors/confirm_delete.html', {'product': product})


@login_required
def order_list(request):
    # 1. دریافت فروشنده کاربر فعلی
    seller_profile = request.user.sellerprofile

    # 2. فیلتر کردن سفارشات بر اساس فروشنده
    orders = Order.objects.filter(items__product__seller=seller_profile).distinct()

    # 3. ارسال داده‌ها به قالب
    context = {
        'orders': orders
    }
    return render(request, 'vendors/vendor_orders.html', context)


def vendor_products_with_reviews(request):
    # دریافت محصولات مرتبط با فروشنده
    seller_profile = request.user.sellerprofile
    products = Product.objects.filter(seller_id=seller_profile).prefetch_related('reviews')

    context = {
        'products': products,
    }

    return render(request, 'vendors/vendor_products_with_reviews.html', context)




















def manage_sellers(request):
    # Logic to manage sellers
    pass


def manage_products(request):
    # Logic to manage products
    pass


def reports(request):
    # Logic to generate reports
    pass

templates/vendors/add_product.html
<!-- vendors/templates/vendors/add_product.html -->
{% extends 'vendors/base.html' %}
{% load custom_filters %}
{% block title %}داشبورد محصولات{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">افزودن محصول جدید</h2>
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.name.label_tag }}
                        {{ form.name|add_class:"form-control" }}
                        {{ form.description.label_tag }}
                        {{ form.description|add_class:"form-control" }}
                        {{ form.price.label_tag }}
                        {{ form.price|add_class:"form-control" }}
                        {{ form.category.label_tag }}
                        {{ form.category|add_class:"form-control" }}
                        {{ form.image.label_tag }}
                        {{ form.image|add_class:"form-control-file" }}
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">افزودن محصول</button>
                </form>
                <a href="{% url 'product_list' %}" class="btn btn-secondary btn-block mt-3">بازگشت به لیست محصولات</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/vendors/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}داشبورد فروشنده{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        .sidebar {
            border-left: 1px solid #ddd;
            padding: 15px; 
            height: 100vh; 
        }
        
        .content {
            padding: 15px; 
        }

        .row {
            height: 100vh; 
        }
    </style>
</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}"> آلدو گالری</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">خروج</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<body>
    <div class="container mt-5">
        <h2>{% block header %}داشبورد فروشنده{% endblock %}</h2>
        <div class="row">
            <!-- سایدبار -->
            <div class="col-md-3 sidebar">
                <h5> حساب کاربری</h5>
                <ul>
                    <li><a href="{% url 'edit_seller_profile' %}"> ویرایش مشخصات</a></li>

                </ul>
                <h5>مدیریت محصولات</h5>
                <ul>
                    <li><a href="{% url 'product_list' %}">لیست محصولات</a></li>
                    <li><a href="{% url 'add_product' %}">اضافه کردن محصول</a></li>
                    <li><a href="{% url 'category_list' %}">لیست دسته‌بندی‌ها</a></li>
                </ul>
                <h5>مدیریت تخفیف‌ها</h5>
                <ul>
                    <li><a href="{% url 'discount_list' %}">لیست تخفیف‌ها</a></li>
                    <li><a href="{% url 'discount_create' %}">اضافه کردن تخفیف</a></li>
                </ul>
                <h5>مدیریت سفارشات</h5>
                <ul>
                    <li><a href="{% url 'vendor_orders' %}">لیست سفارشات</a></li>
                    <li><a href="{% url 'vendor_products_with_reviews' %}">دیدگاه مشتریان </a></li>
                   
                    
                </ul>
                
            </div>
            <!-- پایان سایدبار -->

            <div class="col-md-9 content">
                {% if messages %}
                <ul>
                {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/vendors/category_form.html
{% extends 'vendors/base.html' %}
{% load custom_filters %}


{% block title %} 
    {% if form.instance.pk %}ویرایش دسته بندی{% else %}افزدون دسته{% endif %}  
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">
        {% if form.instance.pk %}ویرایش دسته بندی{% else %}افزدون دسته{% endif %}
    </h1>
    <form method="post" class="form-group">
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.product.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name|add_class:"form-control" }}
            {% for error in form.name.errors %}
                <div class="alert alert-danger mt-2">{{ error }}</div>
            {% endfor %}
        </div>
        
        <button class="btn btn-primary" type="submit">ذخیره</button>
        <a class="btn btn-danger" href="{% url 'category_list' %}">لغو</a>
    </form>
</div>
{% endblock %}

templates/vendors/category_list.html
{% extends 'vendors/base.html' %}

{% block title %}داشبورد محصولات{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">دسته بندی ها</h1>
    <a href="{% url 'category_create' %}" class="btn btn-primary mb-3">افزودن دسته بندی</a>
    
    {% if categories %}
        <div class="list-group">
            {% for category in categories %}
                <div class="list-group-item d-flex justify-content-between align-items-center">
                    <span>{{ category.name }}</span>
                    <div>
                        <a href="{% url 'category_update' category.pk %}" class="btn btn-warning btn-sm">ویرایش</a>
                        <a href="{% url 'category_delete' category.pk %}" class="btn btn-danger btn-sm">حذف</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-info" role="alert">
            هیچ دسته بندی وجود ندارد.
        </div>
    {% endif %}
</div>
{% endblock %}

templates/vendors/confirm_delete.html
{% extends 'vendors/base.html' %}

{% block title %} حذف محصول {% endblock %}

{% block content %}
    <h1>از حذف مطمئنید؟ {{ product.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="تایید">
    </form>

    <a href="{% url 'product_list' %}">لغو</a>
{% endblock %}

templates/vendors/dashboard.html
{% extends 'vendors/base.html' %}
{% load custom_filters %}

{% block title %}داشبورد محصولات{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header text-center">
                    <h4>پروفایل فروشنده</h4>
                </div>
                <div class="card-body">
                    <h5>نام: {{ seller_profile.first_name }} {{ seller_profile.last_name }}</h5>
                    <p>جنسیت: {% if seller_profile.gender == 1 %} آقا {% elif seller_profile.gender == 2 %} خانم {% else %} نامشخص {% endif %} </p>
                    <p>نام فروشگاه: {{ seller_profile.shop_name }}</p>
                    <p>آدرس فروشگاه: {{ seller_profile.shop_address }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <!-- این بخش حذف شد: کارت مدیریت محصولات -->
        </div>
    </div>
</div>
{% endblock %}

templates/vendors/discount_confirm_delete.html
{% extends 'vendors/base.html' %}

{% block title %}  حذف تخفیف  {% endblock %}

{% block content %}


<h1>حذف تخفیف</h1>
<p>مطمئنی میخوای این تخفیف حذف بشه؟ "{{ discount.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">تایید</button>
</form>
<a href="{% url 'discount_list' %}">لغو</a>
{% endblock %}

templates/vendors/discount_form.html
{% extends 'vendors/base.html' %}
{% load custom_filters %}

{% block title %}  
    {% if form.instance.pk %} ویرایش تخفیف 
    {% else %} تخفیف جدید 
    {% endif %}   
{% endblock %}

{% block content %}
<h1>
    {% if form.instance.pk %} ویرایش تخفیف 
    {% else %} تخفیف جدید 
    {% endif %}
</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.product.id_for_label }}">{{ form.product.label }}</label>
        {{ form.product|add_class:"form-control" }}
    </div>
    <div class="form-group">
        <label for="{{ form.discount_type.id_for_label }}">{{ form.discount_type.label }}</label>
        {{ form.discount_type|add_class:"form-control" }}
    </div>
    <div class="form-group">
        <label for="{{ form.value.id_for_label }}">{{ form.value.label }}</label>
        {{ form.value|add_class:"form-control" }}
    </div>
    <div style="margin-top: 0.5rem;" class="btn-group">
        <button class="btn btn-primary" type="submit">افزودن</button>
        <a class="btn btn-danger" style="margin-right: 0.5rem;" href="{% url 'category_list' %}">لغو</a>
    </div>
</form>
{% endblock %}

templates/vendors/discount_list.html
{% extends 'vendors/base.html' %}

{% block title %} تخفیف ها {% endblock %}

{% block content %}

<div class="container mt-4">
    <h1>تخفیف ها</h1>
    <a href="{% url 'discount_create' %}" class="btn btn-primary mb-3">افزودن تخفیف</a>
    <table class="table table-bordered">
        <thead class="thead-light">
            <tr>
                <th>محصول</th>
                <th>نوع تخفیف</th>
                <th>مقدار تخفیف</th>
                <th>عملیات</th>
            </tr>
        </thead>
        <tbody>
            {% for discount in discounts %}
            <tr>
                <td>{{ discount.product.name }}</td>
                <td>{{ discount.get_discount_type_display }}</td> 
                <td>{{ discount.value }}</td>
                <td>
                    <a href="{% url 'discount_update' discount.pk %}" class="btn btn-warning btn-sm">ویرایش</a>
                    <a href="{% url 'discount_delete' discount.pk %}" class="btn btn-danger btn-sm" 
                       onclick="return confirm('آیا از حذف این تخفیف مطمئن هستید؟');">حذف</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/vendors/edit_product.html
{% extends 'vendors/base.html' %}

{% block title %}  ویرایش محصول: {{ product.name }}  {% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>ویرایش محصول: {{ product.name }}</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">ذخیره تغییرات</button>
        </form>
        
        <a href="{% url 'product_list' %}" class="btn btn-secondary mt-3">بازگشت به لیست محصولات</a>
    </div>

{% endblock %}

templates/vendors/product_list.html
{% extends 'vendors/base.html' %}
{% load custom_filters %}

{% block title %}داشبورد محصولات{% endblock %}


{% block content %}
    <div class="container mt-5">
        <h2>لیست محصولات شما</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">نام محصول</th>
                    <th scope="col">قیمت</th>
                    <th scope="col">عملیات</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.price|pnumber_style }} تومان</td>
                    <td>
                        <a href="{% url 'edit_product' product.id %}" class="btn btn-warning">ویرایش</a>
                        <a href="{% url 'delete_product' product.id %}" class="btn btn-danger">حذف</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'add_product' %}" class="btn btn-primary mt-3">افزودن محصول جدید</a>
    </div>
{% endblock %}

templates/vendors/vendor_orders.html
{% extends 'vendors/base.html' %}
{% load custom_filters %}

{% block title %}سفارشات {% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center mb-4">سفارشات شما</h2>
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">شماره سفارش</th>
                <th scope="col">تاریخ</th>
                <th scope="col">مجموع مبلغ</th>
                <th scope="col">آدرس</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.created_at|format_date }}</td>
                <td>{{ order.total_amount|pnumber_style }}</td>
                <td>{{ order.address }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4" class="text-center">هیچ سفارشی وجود ندارد.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/vendors/vendor_products_with_reviews.html
{% extends 'vendors/base.html' %}
{% load custom_filters %}

{% block title %}نظرات محصولات شما {% endblock %}

{% block content %}
    <h1 class="text-center my-4">نظرات و امتیازات محصولات شما</h1>
    <ul class="list-unstyled">
        {% for product in products %}
            {% for review in product.reviews.all %}
                <li class="review-item mb-4 p-3 border rounded shadow-sm">
                    <h5 class="text-muted">{{ product.name }}</h5>
                    <p class="mb-1">
                        {% for star in "12345" %}
                            {% if star|add:0 <= review.rating %}
                                <span class="text-warning">&#9733;</span>  <!-- ستاره پر شده -->
                            {% else %}
                                <span class="text-secondary">&#9734;</span> <!-- ستاره خالی -->
                            {% endif %}
                        {% endfor %}
                    </p>
                    <p class="mb-1">نظر: {{ review.comment }}</p>
                    <p class="text-muted small">تاریخ: {{ review.created_at|date:"Y-m-d" }}</p>
                </li>
            {% empty %}
                <p>هیچ نظری برای این محصول وجود ندارد.</p>
            {% endfor %}
        {% endfor %}
    </ul>

    <style>
        .review-item {
            transition: all 0.3s ease;
        }

        .review-item:hover {
            transform: scale(1.02);
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        }
    </style>
{% endblock %}